# Generated by Django 6.0.1 on 2026-09-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expences',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('electronic', 'Electronic'), ('bill', 'Bill'), ('medical', 'Medical'), ('entertainment', 'Entertainment'), ('transport', 'Transport'), ('other', 'Other')], max_length=20),
        ),
    ]
